In [42]:
#count

import numpy as np
def determine() : 
    line = np.array([3, 4 ,-10])
    learningRate = 0.1
    points = np.array([1, 1, 1])
    # bias = 1

    print(line)
    adjustedPoints = learningRate * points
    print(adjustedPoints)
    newLine = line + adjustedPoints
    print(newLine)
    # print(np.sum(newLine))

    newValue = np.sum(newLine)
    print("determine value =", newValue)

determine()

[  3   4 -10]
[0.1 0.1 0.1]
[ 3.1  4.1 -9.9]
determine value = -2.700000000000001


In [44]:
count = 0
for i in range(0, len(newLine)) :
    if newValue <= 0 :
        determine()

[  3   4 -10]
[0.1 0.1 0.1]
[ 3.1  4.1 -9.9]
determine value = -2.700000000000001
[  3   4 -10]
[0.1 0.1 0.1]
[ 3.1  4.1 -9.9]
determine value = -2.700000000000001
[  3   4 -10]
[0.1 0.1 0.1]
[ 3.1  4.1 -9.9]
determine value = -2.700000000000001
