1. Refer to lin_alg_for_ml_by_ja_br | ch14

In [1]:
import numpy as np
import scipy as sp
from scipy.linalg import lu

# Formula 
A = L dot U

In [2]:
# 3 x 3 square Matrix
D = np.array([
             [1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]
             ])
print("D.shape : ", D.shape, "\nD : \n", D)

print("\n#### FACTOR - DECMOPOSITION ####")

L = np.array([
             [1, 0, 0],
             [4, 1, 0],
             [7, 2, 1]
             ])

U = np.array([
             [1, 2, 3],
             [0, -3, -6],
             [0, 0, 0]
             ])

print("\n>> L.shape : ", L.shape, "\n>> L : \n", L, 
     "\n\n>> U.shape : ", U.shape, "\n>> U : \n", U
     )


print("\n#### RECONSTRUCT ####")

L_dot_U = np.dot(L, U)
print("\n>> L_dot_U.shape : ", L_dot_U.shape, "\n>> L_dot_U : \n", L_dot_U)



D.shape :  (3, 3) 
D : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

#### FACTOR - DECMOPOSITION ####

>> L.shape :  (3, 3) 
>> L : 
 [[1 0 0]
 [4 1 0]
 [7 2 1]] 

>> U.shape :  (3, 3) 
>> U : 
 [[ 1  2  3]
 [ 0 -3 -6]
 [ 0  0  0]]

#### RECONSTRUCT ####

>> L_dot_U.shape :  (3, 3) 
>> L_dot_U : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


# Formula
A = P dot dot L dot U

In [3]:
# 3 x 3 square Matrix
D = np.array([
             [1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]
             ])
print("D.shape : ", D.shape, "\nD : \n", D)

print("\n#### FACTOR - DECMOP ####")

P, L, U = sp.linalg.lu(D)
print("\nP.shape : ", P.shape, "\nP : \n", P, 
      "\n\nL.shape : ", L.shape, "\nL : \n", L, 
     "\n\nU.shape : ", U.shape, "\nU : \n", U
     )


print("\n#### RECONSTRUCT ####")
J = P.dot(L).dot(U)
print("J.shape : ", J.shape, "\nJ : \n", J)

# another way to write J
B = np.dot(np.dot(P, L), U)
print("B.shape : ", B.shape, "\nB : \n", B)

D.shape :  (3, 3) 
D : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

#### FACTOR - DECMOP ####

P.shape :  (3, 3) 
P : 
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]] 

L.shape :  (3, 3) 
L : 
 [[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]] 

U.shape :  (3, 3) 
U : 
 [[ 7.00000000e+00  8.00000000e+00  9.00000000e+00]
 [ 0.00000000e+00  8.57142857e-01  1.71428571e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.58603289e-16]]


NameError: name 'J' is not defined