About

- Comes from CH 5 Finding Road Markings Using OpenCV of Applied DL and CV for Self-Driving Cars

- Skill : practice reshaping array
- Columns : X1, Y1, X2, Y2
- Rows : 
        X1_11, Y1_12, X2_13, Y2_14
        X1_21, Y1_22, X2_23, Y2_24
        ...,  
        X1_N1, Y1_N2, X2_N3, Y2_N4

In [4]:
import numpy as np

In [6]:
lines = np.array([[[ 846,  373, 942,  373]],

 [[ 823,  369,  881,  369],],

 [[ 900,  364,  950,  364],],

 [[ 920,  367,  971,  367],],

 [[ 945,  357, 1022,  357],],

 [[ 875,  360,  942,  360],],

 [[ 935,  365,  997,  365],],

 [[ 766,  373,  832,  373],],

 [[ 892,  352,  935,  352],],

 [[ 823,  367,  863,  367],],

 [[ 900,  344,  966,  344],],

 [[ 843,  347,  887,  347],],

 [[ 883,  351,  969,  348],],

 [[ 953,  353, 1001,  353],],

 [[ 917,  363,  965,  362],],

 [[ 933,  369,  994,  369],],

 [[ 817,  355,  878,  355],],

 [[ 847,  359,  893,  359],],

 [[ 806,  339,  849,  339],],

 [[ 973,  373, 1026,  373],],

 [[ 249,  365,  299,  365],],

 [[ 816,  337,  864,  337],],

 [[ 874,  343,  945,  343],],

 [[ 857,  353,  922,  354],],

 [[1015,  368, 1066,  368],],

 [[ 801,  365,  858,  366],],

 [[ 833,  344,  907,  341],],

 [[ 749,  350,  806,  349],],

 [[ 796,  356,  844,  356],],

 [[ 798,  343,  873,  339],],

 [[ 771,  337,  830,  333],],

 [[ 805,  348,  848,  348],],

 [[ 275,  358,  318,  358],],

 [[ 889,  351,  962,  349],],

 [[ 864,  346,  928,  347],],

 [[ 838,  333,  878,  333],],

 [[ 799,  345,  850,  342],],

 [[ 947,  366, 1002,  366],],

 [[ 875,  337,  925,  337],],

 [[ 757,  301,  800,  310],],

 [[1040,  370, 1080,  370],],

 [[ 842,  328,  882,  328],],

 [[ 808,  310,  869,  324],],

 [[ 826,  325,  869,  325],],

 [[ 764,  321,  809,  319],],

 [[ 810,  353,  850,  353],],

 [[ 813,  374,  875 , 374],]])
print(lines, np.shape(lines))

[[[ 846  373  942  373]]

 [[ 823  369  881  369]]

 [[ 900  364  950  364]]

 [[ 920  367  971  367]]

 [[ 945  357 1022  357]]

 [[ 875  360  942  360]]

 [[ 935  365  997  365]]

 [[ 766  373  832  373]]

 [[ 892  352  935  352]]

 [[ 823  367  863  367]]

 [[ 900  344  966  344]]

 [[ 843  347  887  347]]

 [[ 883  351  969  348]]

 [[ 953  353 1001  353]]

 [[ 917  363  965  362]]

 [[ 933  369  994  369]]

 [[ 817  355  878  355]]

 [[ 847  359  893  359]]

 [[ 806  339  849  339]]

 [[ 973  373 1026  373]]

 [[ 249  365  299  365]]

 [[ 816  337  864  337]]

 [[ 874  343  945  343]]

 [[ 857  353  922  354]]

 [[1015  368 1066  368]]

 [[ 801  365  858  366]]

 [[ 833  344  907  341]]

 [[ 749  350  806  349]]

 [[ 796  356  844  356]]

 [[ 798  343  873  339]]

 [[ 771  337  830  333]]

 [[ 805  348  848  348]]

 [[ 275  358  318  358]]

 [[ 889  351  962  349]]

 [[ 864  346  928  347]]

 [[ 838  333  878  333]]

 [[ 799  345  850  342]]

 [[ 947  366 1002  366]]

 [[ 875  337

In [57]:
final = []
print(len(lines))
# Get each line and it's shape
for line in range(len(lines)):
    # print(line, np.shape(line), lines[line])
    print(line)
    a_line = lines[line]
    for row in range(len(a_line)):
        print(row, a_line[row])
        # v_stack = np.v_stack(a_line[row], a_line[row])
        # for value in row:
        #     print(row[value])
            

47
0
0 [846 373 942 373]
1
0 [823 369 881 369]
2
0 [900 364 950 364]
3
0 [920 367 971 367]
4
0 [ 945  357 1022  357]
5
0 [875 360 942 360]
6
0 [935 365 997 365]
7
0 [766 373 832 373]
8
0 [892 352 935 352]
9
0 [823 367 863 367]
10
0 [900 344 966 344]
11
0 [843 347 887 347]
12
0 [883 351 969 348]
13
0 [ 953  353 1001  353]
14
0 [917 363 965 362]
15
0 [933 369 994 369]
16
0 [817 355 878 355]
17
0 [847 359 893 359]
18
0 [806 339 849 339]
19
0 [ 973  373 1026  373]
20
0 [249 365 299 365]
21
0 [816 337 864 337]
22
0 [874 343 945 343]
23
0 [857 353 922 354]
24
0 [1015  368 1066  368]
25
0 [801 365 858 366]
26
0 [833 344 907 341]
27
0 [749 350 806 349]
28
0 [796 356 844 356]
29
0 [798 343 873 339]
30
0 [771 337 830 333]
31
0 [805 348 848 348]
32
0 [275 358 318 358]
33
0 [889 351 962 349]
34
0 [864 346 928 347]
35
0 [838 333 878 333]
36
0 [799 345 850 342]
37
0 [ 947  366 1002  366]
38
0 [875 337 925 337]
39
0 [757 301 800 310]
40
0 [1040  370 1080  370]
41
0 [842 328 882 328]
42
0 [808 310 869